function [bboxes, labels, scores, numObjects, annotatedImage] = threadedYOLODetection(myImg, detectorRef)
    detector = detectorRef.Value;

    [bboxes, scores, labels] = detect(detector, myImg, Threshold = 0.7);

    numObjects = size(bboxes, 1);
    annotatedImage = insertObjectAnnotation(im2uint8(myImg), ...
        'Rectangle', ...
        bboxes, ...
        string(labels) + ": "+string(scores), ...
        'Color', 'cyan');
end