function matlab_pose = ros2MLPose(p)
    % gazebo_msgs/GetModelStateResponse
    if strcmp(p.MessageType, 'gazebo_msgs/GetModelStateResponse')
        pos = [p.Pose.Position.X, ...
               p.Pose.Position.Y, ...
               p.Pose.Position.Z];

        q = UnitQuaternion(p.Pose.Orientation.W, ...
                           [p.Pose.Orientation.X, ...
                            p.Pose.Orientation.Y, ...
                            p.Pose.Orientation.Z]);

    % 'geometry_msgs/TransformStamped'
    elseif strcmp(p.MessageType, 'geometry_msgs/TransformStamped')
        pos = [p.Transform.Translation.X, ...
               p.Transform.Translation.Y, ...
               p.Transform.Translation.Z];

        q = UnitQuaternion(p.Transform.Rotation.W, ...
                           [p.Transform.Rotation.X, ...
                            p.Transform.Rotation.Y, ...
                            p.Transform.Rotation.Z]);
    end

    matlab_pose = transl(pos) * q.T;
end
