function matlab_pose = ros2MLPose(poseMsg)
    % gazebo_msgs/GetModelStateResponse
    if strcmp(poseMsg.MessageType, 'gazebo_msgs/GetModelStateResponse')
        pos = [poseMsg.Pose.Position.X, ...
               poseMsg.Pose.Position.Y, ...
               poseMsg.Pose.Position.Z];

        q = UnitQuaternion(poseMsg.Pose.Orientation.W, ...
                           [poseMsg.Pose.Orientation.X, ...
                            poseMsg.Pose.Orientation.Y, ...
                            poseMsg.Pose.Orientation.Z]);

    % 'geometry_msgs/TransformStamped'
    elseif strcmp(poseMsg.MessageType, 'geometry_msgs/TransformStamped')
        pos = [poseMsg.Transform.Translation.X, ...
               poseMsg.Transform.Translation.Y, ...
               poseMsg.Transform.Translation.Z];

        q = UnitQuaternion(poseMsg.Transform.Rotation.W, ...
                           [poseMsg.Transform.Rotation.X, ...
                            poseMsg.Transform.Rotation.Y, ...
                            poseMsg.Transform.Rotation.Z]);
    end

    matlab_pose = transl(pos) * q.T;
end
